/**
 * HaloITSM notification apply rules
 */

apply Notification "Halo Notification Host" to Host {
  import "Halo-Notification-Host"

  times.end = 9h
  interval  = 3h
  period    = "24x7"
  assign where host.address
  states = [ Down, Up ]
  types  = [ Custom, FlappingEnd, FlappingStart, Problem, Recovery ]
  users  = [ "halo-digital-user" ]
}

apply Notification "Halo Notification Service" to Service {
  import "Halo-Notification-Service"

  times.end = 9h
  interval  = 3h
  period    = "24x7"
  assign where service.host
  states = [ Critical, OK, Warning ]
  types  = [ Custom, FlappingEnd, FlappingStart, Problem, Recovery ]
  users  = [ "halo-digital-user" ]
}
